/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELCOT
 */
public class member extends javax.swing.JFrame {

    /**
     * Creates new form member
     */
    public member() {
        initComponents();
        Connect();
    }
    
    
    Connection con;
     PreparedStatement pst;
     DefaultTableModel df;
    
     
     public void Connect()
     {  
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gym management","root", "");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Trainer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Trainer.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        txtmlname = new javax.swing.JTextField();
        txtmaddress = new javax.swing.JTextField();
        txtmdob = new com.toedter.calendar.JDateChooser();
        txtmphone = new javax.swing.JTextField();
        txtmgen = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtmsub = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtmamnt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtmtrainer = new javax.swing.JTextField();
        txtsdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 20, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 70, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 120, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 170, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("phone no");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 270, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Startdate");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 220, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 320, 90, 30);

        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtmname);
        txtmname.setBounds(220, 20, 250, 30);

        txtmlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmlnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtmlname);
        txtmlname.setBounds(220, 70, 250, 30);

        txtmaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtmaddress);
        txtmaddress.setBounds(220, 170, 250, 30);
        jPanel1.add(txtmdob);
        txtmdob.setBounds(220, 120, 250, 30);

        txtmphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmphoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtmphone);
        txtmphone.setBounds(220, 270, 250, 30);

        txtmgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(txtmgen);
        txtmgen.setBounds(220, 320, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("subscription");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 370, 120, 30);

        txtmsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "monthly", "3month", "6month", "1year" }));
        txtmsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmsubActionPerformed(evt);
            }
        });
        jPanel1.add(txtmsub);
        txtmsub.setBounds(220, 370, 250, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Amount");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 420, 90, 20);
        jPanel1.add(txtmamnt);
        txtmamnt.setBounds(220, 420, 250, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 510, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("cancel");
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 510, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Trainer");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 470, 80, 22);

        txtmtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmtrainerActionPerformed(evt);
            }
        });
        jPanel1.add(txtmtrainer);
        txtmtrainer.setBounds(220, 470, 250, 30);
        jPanel1.add(txtsdate);
        txtsdate.setBounds(220, 220, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ragul\\final1.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 530, 560);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Member Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtmlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmlnameActionPerformed

    private void txtmaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaddressActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtmtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmtrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmtrainerActionPerformed

    private void txtmsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsubActionPerformed

    private void txtmphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmphoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname = txtmname.getText();
        String lname = txtmlname.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("DD-MM_YYYY");
        String dob = sdf.format(txtmdob.getDate());
        String madd = txtmaddress.getText();
        String mdate = sdf.format(txtsdate.getDate());
        String mphone = txtmphone.getText();
        String mgenn = txtmgen.getSelectedItem().toString();
        String msub = txtmsub.getSelectedItem().toString();
        String mamount = txtmamnt.getText();
        String mtrainer = txtmtrainer.getText();
        
         try {
            pst = con.prepareStatement("insert into  member(fname,lname,date of birth,address,date of join,phone no,generation,subscription,amount,trainer)values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, fname);
            pst.setString(2,lname);
            pst.setString(3,madd);
            pst.setString(4,mdate);
            pst.setString(5,mphone);
            pst.setString(6,mgenn);
            pst.setString(7,msub);
            pst.setString(8,mamount);
            pst.setString(9,mtrainer);
            pst.setString(10,dob);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Member added");
            
            
            txttrainer.requestFocus();    
        } catch (SQLException ex) {
            Logger.getLogger(member.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmaddress;
    private javax.swing.JTextField txtmamnt;
    private com.toedter.calendar.JDateChooser txtmdob;
    private javax.swing.JComboBox<String> txtmgen;
    private javax.swing.JTextField txtmlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmphone;
    private javax.swing.JComboBox<String> txtmsub;
    private javax.swing.JTextField txtmtrainer;
    private com.toedter.calendar.JDateChooser txtsdate;
    // End of variables declaration//GEN-END:variables
}
